# Generated by Django 5.2.17 on 2026-08-17 08:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailySnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snapshot_date', models.DateField(unique=True)),
                ('data', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_id', models.CharField(max_length=20, unique=True)),
                ('password_hash', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=100)),
                ('last_login_at', models.DateTimeField(blank=True, null=True)),
                ('last_activity_at', models.DateTimeField(blank=True, null=True)),
                ('is_active_session', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ScopeHeading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading_name', models.CharField(choices=[('branding', 'Branding'), ('construction', 'Construction'), ('electrical', 'Electrical'), ('operation', 'Operation'), ('safety', 'Safety'), ('regulatory_documents', 'Regulatory Documents'), ('extra_addons', 'Extra Addons')], max_length=30)),
                ('departments', models.ManyToManyField(blank=True, related_name='scope_headings', to='tracker.department')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scope_headings', to='tracker.location')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_type', models.CharField(choices=[('normal', 'Normal'), ('regulatory_doc', 'Regulatory Document'), ('action_point', 'Action Point')], default='normal', max_length=20)),
                ('name', models.CharField(max_length=200)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('actual_end_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('not_done', 'Not Done'), ('in_progress', 'In Progress'), ('done', 'Done')], default='not_done', max_length=20)),
                ('doc_status', models.CharField(blank=True, choices=[('received', 'Received'), ('waiting_approval', 'Waiting Approval'), ('sent_approved', 'Sent and Approved')], max_length=20, null=True)),
                ('funds_type', models.CharField(choices=[('na', 'N/A'), ('none', 'None'), ('amount', 'Amount')], default='na', max_length=10)),
                ('funds_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('assignee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='tracker.manager')),
                ('heading', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='tracker.scopeheading')),
                ('parent_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='action_points', to='tracker.task')),
            ],
        ),
        migrations.CreateModel(
            name='Remark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tracker.manager')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remarks', to='tracker.task')),
            ],
        ),
        migrations.CreateModel(
            name='AuditLogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_changed', models.CharField(max_length=50)),
                ('old_value', models.CharField(blank=True, max_length=255)),
                ('new_value', models.CharField(blank=True, max_length=255)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tracker.manager')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_log', to='tracker.task')),
            ],
        ),
        migrations.CreateModel(
            name='ManagerDepartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.department')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.manager')),
            ],
            options={
                'unique_together': {('manager', 'department')},
            },
        ),
    ]
