# Generated by Django 5.2.17 on 2026-08-17 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_location_archived_at_location_is_archived'),
    ]

    operations = [
        migrations.AddField(
            model_name='scopeheading',
            name='custom_label',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='scopeheading',
            name='heading_name',
            field=models.CharField(choices=[('branding', 'Branding'), ('construction', 'Construction'), ('electrical', 'Electrical'), ('operation', 'Operation'), ('safety', 'Safety'), ('regulatory_documents', 'Regulatory Documents'), ('custom', 'Custom')], max_length=30),
        ),
    ]
