# Generated by Django 5.2.17 on 2026-08-25 12:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_passwordresetlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_locations', to='tracker.department'),
        ),
        migrations.AddField(
            model_name='location',
            name='shared_with_managers',
            field=models.ManyToManyField(blank=True, related_name='shared_locations', to='tracker.manager'),
        ),
        migrations.AddField(
            model_name='manager',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff', to='tracker.department'),
        ),
        migrations.AddField(
            model_name='manager',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
    ]
